# This is a basic workflow to help you get started with Actions

name: Build Polaris

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt install -y make xorriso libarchive-tools rsync

      # Runs a single command using the runners shell
      - name: Clone source of Polaris
        run: git clone https://github.com/NSG650/Polaris.git

      - name: Get Jinx
        run: |
          cd Polaris
          wget https://raw.githubusercontent.com/mintsuki/jinx/master/jinx
          chmod +x jinx

      - name: Apply Patch
        run: |
          cd Polaris
          patch -p0 < ../clang.patch

      - name: Build userspace
        run: |
          cd Polaris
          make userspace-full

      - name: Make ISO
        run: |
          cd Polaris
          make

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: polaris
          path: Polaris/polaris.iso
      
